### ISSUE TITLE
error CS0066  in SplineNode.cs

### ISSUE THREAD

**Issue by tewfik-dj** [methusalah/SplineMesh#57]
Hi, thank you so much for the great tool and the open source initiative! Great tool.

Sadly, I wasn't able to make it work on Unity 2022.1.5f1 (haven't tested on other versions at the moment)

I get the following error

````
Assets\SplineMesh\Scripts\Bezier\SplineNode.cs(105,35): error CS0066: 'SplineNode.Changed': event must be of a delegate type
````

I tried the following patch but to no avail (I'm not very familiar with events and delegates in c#)

https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs0066

```c#
public delegate EventHandler();
public event EventHandler Changed;
```

### How to reproduce

- Import the package SplineMesh using Package manager in Unity 2022.1.5f1
- Open the show case scene
- Script SplineNode.cs won't compile (CS0066)

A screenshot of the error if this could help :)
https://pasteboard.co/mN3L28uBbZRz.png

Many thanks!

https://github.com/methusalah/SplineMesh/blob/71c4591f5531af06e8555fa76c8ece0c466ee3e8/Assets/SplineMesh/Scripts/Bezier/SplineNode.cs#L105

**Comment by tewfik-dj** [comment]
Update - when used in a new (fresh) project it works perfectly on Unity 2022.1.5f1 
This means there is a conflict with another package that needs to be addressed - I will investigate and hopefully provide an explanation / fix.

Thanks!

**Comment by tewfik-dj** [comment]
Closing this issue as it has to do with another asset (Gley Traffic system) that declares EventHandler (which is not right) which causes the mentioned issue.
